[app]
crate = "blogwriter"

[frontend]
dir = "app"

[codegen]
out = "app/src/bindings.ts"

[bundle]
identifier = "no.gets.blogwriter"
name = "BlogWriter"
version = "1.0.1"

[database]
url = "sqlite://blogwriter.db?mode=rwc"
migrations = "migrations"
