// Generated by Ratatosk (`rata codegen`). Do not edit by hand.


import { invoke } from "@elyra/runtime";

/**  A generated article and its publish status. */
export type Article = {
	id: number,
	site_id: number,
	title: string,
	slug: string,
	excerpt: string,
	body: string,
	/**  The topic the article was generated for (drives rotation/generation). */
	theme: string,
	/**  Blog category to file the article under (defaults to the theme). */
	category: string,
	/**  `draft` | `published` | `failed`. */
	status: string,
	/**  Id returned by the Laravel site on publish. */
	remote_id: string,
	error: string,
	/**  Web-optimized cover image as a data URL (`data:image/jpeg;base64,...`). */
	image: string,
	created_at: number,
	updated_at: number,
	published_at: number,
};

export type SettingsView = {
	anthropic_key_set: boolean,
	model: string,
	openai_key_set: boolean,
	image_model: string,
};

/**  A registered Laravel site that receives generated articles. */
export type Site = {
	id: number,
	name: string,
	/**  What the site is about (audience, purpose, voice) — steers generation. */
	description: string,
	/**  Base URL of the Laravel site, e.g. `https://blog.example.com`. */
	base_url: string,
	/**  API path that accepts new articles (default `/api/articles`). */
	api_path: string,
	/**  Bearer token for the Laravel endpoint. */
	token: string,
	/**  Comma-separated topics/themes to write about. */
	themes: string,
	tone: string,
	language: string,
	/**  `hourly` | `daily` | `weekly` | `monthly` | `manual`. */
	cadence: string,
	active: boolean,
	/**  Publish immediately after generating (vs. leave as a draft). */
	auto_publish: boolean,
	/**  Generate a cover image for each article. */
	image_enabled: boolean,
	/**  Illustration style, e.g. `flat isometric` or `risograph grain`. */
	image_style: string,
	/**  Aspect ratio, e.g. `16:9`. */
	image_format: string,
	/**  Unix seconds: when the next article is due. */
	next_run_at: number,
	created_at: number,
	updated_at: number,
};

export type UpdateCheck = {
	available: boolean,
	/**  Latest version when available, otherwise the running version. */
	version: string,
	notes: string,
	current: string,
};

export const api = {
  check_for_update(): Promise<UpdateCheck> {
    return invoke("check_for_update");
  },
  delete_article(article_id: number): Promise<null> {
    return invoke("delete_article", article_id);
  },
  delete_site(id: number): Promise<null> {
    return invoke("delete_site", id);
  },
  generate_now(site_id: number): Promise<Article> {
    return invoke("generate_now", site_id);
  },
  get_settings(): Promise<SettingsView> {
    return invoke("get_settings");
  },
  get_site(id: number): Promise<{
	id: number,
	name: string,
	/**  What the site is about (audience, purpose, voice) — steers generation. */
	description: string,
	/**  Base URL of the Laravel site, e.g. `https://blog.example.com`. */
	base_url: string,
	/**  API path that accepts new articles (default `/api/articles`). */
	api_path: string,
	/**  Bearer token for the Laravel endpoint. */
	token: string,
	/**  Comma-separated topics/themes to write about. */
	themes: string,
	tone: string,
	language: string,
	/**  `hourly` | `daily` | `weekly` | `monthly` | `manual`. */
	cadence: string,
	active: boolean,
	/**  Publish immediately after generating (vs. leave as a draft). */
	auto_publish: boolean,
	/**  Generate a cover image for each article. */
	image_enabled: boolean,
	/**  Illustration style, e.g. `flat isometric` or `risograph grain`. */
	image_style: string,
	/**  Aspect ratio, e.g. `16:9`. */
	image_format: string,
	/**  Unix seconds: when the next article is due. */
	next_run_at: number,
	created_at: number,
	updated_at: number,
} | null> {
    return invoke("get_site", id);
  },
  install_update(): Promise<null> {
    return invoke("install_update");
  },
  list_articles(site_id: number): Promise<Article[]> {
    return invoke("list_articles", site_id);
  },
  list_sites(): Promise<Site[]> {
    return invoke("list_sites");
  },
  publish_article(article_id: number): Promise<Article> {
    return invoke("publish_article", article_id);
  },
  regenerate_image(article_id: number): Promise<Article> {
    return invoke("regenerate_image", article_id);
  },
  save_settings(anthropic_key: string, model: string, openai_key: string, image_model: string): Promise<null> {
    return invoke("save_settings", anthropic_key, model, openai_key, image_model);
  },
  save_site(site: Site): Promise<Site> {
    return invoke("save_site", site);
  },
  update_article(article_id: number, title: string, excerpt: string, body: string, theme: string, category: string): Promise<Article> {
    return invoke("update_article", article_id, title, excerpt, body, theme, category);
  },
};

